name: Update Book Listings

on:
  schedule:
    - cron: '30 12 * * *'  # Runs at 12:00 PM UTC every day

jobs:
  update_books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository # allows github actions to access the contents of the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push if Changes
        run: |
          git config --global user.email "bchau03@gmail.com"
          git config --global user.name "Brandon Chau"
          git add -A
          git commit -m "Updated bestseller list" || echo "No changes to commit"
          git push
